# Generated by Django 3.1.2 on 2020-12-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
