# Generated by Django 3.1.2 on 2020-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201211_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.CharField(max_length=10),
        ),
    ]
