# Generated by Django 3.1.2 on 2020-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201211_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.CharField(max_length=10),
        ),
    ]
