# Generated by Django 3.1.2 on 2020-12-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201211_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productDate',
        ),
    ]
