# Generated by Django 3.1.2 on 2020-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201211_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.IntegerField(),
        ),
    ]
