# Generated by Django 3.1.2 on 2020-12-11 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201211_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pinCode',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
