# Generated by Django 3.1.2 on 2020-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customer_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pinCode',
            field=models.CharField(max_length=6),
        ),
    ]
