# Generated by Django 3.1.2 on 2020-12-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201211_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pinCode',
        ),
    ]
