# Generated by Django 3.1.2 on 2020-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pinCode',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
