# Generated by Django 3.1.2 on 2020-12-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customer_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.CharField(max_length=10),
        ),
    ]
