# Generated by Django 3.1.2 on 2020-12-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20201215_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productDesc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productPrice',
            new_name='Price',
        ),
    ]
